import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:hive_flutter/hive_flutter.dart';
import '../config/app_constants.dart';
import '../models/user_model.dart';
import '../models/semester_model.dart';
import '../models/course_model.dart';
import '../models/group_model.dart';
import '../models/announcement_model.dart';
import '../models/assignment_model.dart';
import '../models/assignment_submission_model.dart';
import '../models/quiz_model.dart';
import '../models/question_model.dart';
import '../models/quiz_submission_model.dart';
import '../models/material_model.dart';
import '../models/forum_topic_model.dart';
import '../models/forum_reply_model.dart';
import '../models/message_model.dart';
import '../models/notification_model.dart';

/// Hive Service
/// Handles offline caching and local data storage
class HiveService {
  static HiveService? _instance;
  bool _isInitialized = false;

  HiveService._();

  static HiveService get instance {
    _instance ??= HiveService._();
    return _instance!;
  }

  /// Initialize Hive and open boxes
  Future<void> initialize() async {
    // Check if already initialized to prevent duplicate initialization
    if (_isInitialized) {
      print('Hive already initialized');
      return;
    }

    try {
      // Initialize Hive for Flutter
      await Hive.initFlutter();

      // Register adapters (generated by build_runner)
      if (!Hive.isAdapterRegistered(AppConstants.hiveTypeIdUser)) {
        Hive.registerAdapter(UserModelAdapter());
      }
      if (!Hive.isAdapterRegistered(AppConstants.hiveTypeIdSemester)) {
        Hive.registerAdapter(SemesterModelAdapter());
      }
      if (!Hive.isAdapterRegistered(AppConstants.hiveTypeIdCourse)) {
        Hive.registerAdapter(CourseModelAdapter());
      }
      if (!Hive.isAdapterRegistered(AppConstants.hiveTypeIdGroup)) {
        Hive.registerAdapter(GroupModelAdapter());
      }
      if (!Hive.isAdapterRegistered(AppConstants.hiveTypeIdAnnouncement)) {
        Hive.registerAdapter(AnnouncementModelAdapter());
      }
      if (!Hive.isAdapterRegistered(AppConstants.hiveTypeIdAssignment)) {
        Hive.registerAdapter(AssignmentModelAdapter());
      }
      if (!Hive.isAdapterRegistered(AppConstants.hiveTypeIdAssignmentSubmission)) {
        Hive.registerAdapter(AssignmentSubmissionModelAdapter());
      }
      if (!Hive.isAdapterRegistered(AppConstants.hiveTypeIdQuiz)) {
        Hive.registerAdapter(QuizModelAdapter());
      }
      if (!Hive.isAdapterRegistered(AppConstants.hiveTypeIdQuestion)) {
        Hive.registerAdapter(QuestionModelAdapter());
      }
      if (!Hive.isAdapterRegistered(AppConstants.hiveTypeIdQuizSubmission)) {
        Hive.registerAdapter(QuizSubmissionModelAdapter());
      }
      if (!Hive.isAdapterRegistered(AppConstants.hiveTypeIdMaterial)) {
        Hive.registerAdapter(MaterialModelAdapter());
      }
      if (!Hive.isAdapterRegistered(AppConstants.hiveTypeIdForumTopic)) {
        Hive.registerAdapter(ForumTopicModelAdapter());
      }
      if (!Hive.isAdapterRegistered(AppConstants.hiveTypeIdForumReply)) {
        Hive.registerAdapter(ForumReplyModelAdapter());
      }
      if (!Hive.isAdapterRegistered(AppConstants.hiveTypeIdMessage)) {
        Hive.registerAdapter(MessageModelAdapter());
      }
      if (!Hive.isAdapterRegistered(AppConstants.hiveTypeIdNotification)) {
        Hive.registerAdapter(NotificationModelAdapter());
      }

      // Open boxes
      await _openBoxes();

      _isInitialized = true;
      print('Hive initialized successfully');
    } catch (e) {
      print('Hive initialization error: $e');
      // On web, Hive initialization might fail due to platform limitations
      // We'll continue without caching rather than blocking the app
      if (kIsWeb) {
        print('Warning: Hive caching disabled on web platform');
        _isInitialized = false;
      } else {
        throw Exception('Failed to initialize Hive: ${e.toString()}');
      }
    }
  }

  /// Open all Hive boxes
  Future<void> _openBoxes() async {
    await Hive.openBox(AppConstants.hiveBoxUsers);
    await Hive.openBox(AppConstants.hiveBoxSemesters);
    await Hive.openBox(AppConstants.hiveBoxCourses);
    await Hive.openBox(AppConstants.hiveBoxGroups);
    await Hive.openBox(AppConstants.hiveBoxAnnouncements);
    await Hive.openBox(AppConstants.hiveBoxAssignments);
    await Hive.openBox(AppConstants.hiveBoxQuizzes);
    await Hive.openBox(AppConstants.hiveBoxMaterials);
    await Hive.openBox(AppConstants.hiveBoxNotifications);
    await Hive.openBox(AppConstants.hiveBoxCache);
    await Hive.openBox(AppConstants.hiveBoxSettings);
  }

  /// Get a box by name
  Box? _getBox(String boxName) {
    if (!_isInitialized) {
      return null;
    }
    if (!Hive.isBoxOpen(boxName)) {
      print('Warning: Box $boxName is not open');
      return null;
    }
    return Hive.box(boxName);
  }

  /// Save data to cache
  Future<void> save({
    required String boxName,
    required String key,
    required dynamic value,
  }) async {
    try {
      if (!_isInitialized) {
        print('Hive not initialized, skipping save');
        return;
      }
      final box = _getBox(boxName);
      if (box == null) return;
      await box.put(key, value);
    } catch (e) {
      print('Hive save error: $e');
      // Don't throw, just log - caching is optional
    }
  }

  /// Get data from cache
  dynamic get({
    required String boxName,
    required String key,
    dynamic defaultValue,
  }) {
    try {
      if (!_isInitialized) {
        return defaultValue;
      }
      final box = _getBox(boxName);
      if (box == null) return defaultValue;
      return box.get(key, defaultValue: defaultValue);
    } catch (e) {
      print('Hive get error: $e');
      return defaultValue;
    }
  }

  /// Delete data from cache
  Future<void> delete({
    required String boxName,
    required String key,
  }) async {
    try {
      if (!_isInitialized) return;
      final box = _getBox(boxName);
      if (box == null) return;
      await box.delete(key);
    } catch (e) {
      print('Hive delete error: $e');
      // Don't throw, just log - caching is optional
    }
  }

  /// Clear all data from a box
  Future<void> clearBox(String boxName) async {
    try {
      if (!_isInitialized) return;
      final box = _getBox(boxName);
      if (box == null) return;
      await box.clear();
    } catch (e) {
      print('Hive clear box error: $e');
      // Don't throw, just log - caching is optional
    }
  }

  /// Get all keys from a box
  List<dynamic> getAllKeys(String boxName) {
    try {
      if (!_isInitialized) return [];
      final box = _getBox(boxName);
      if (box == null) return [];
      return box.keys.toList();
    } catch (e) {
      print('Hive get all keys error: $e');
      return [];
    }
  }

  /// Get all values from a box
  List<dynamic> getAllValues(String boxName) {
    try {
      if (!_isInitialized) return [];
      final box = _getBox(boxName);
      if (box == null) return [];
      return box.values.toList();
    } catch (e) {
      print('Hive get all values error: $e');
      return [];
    }
  }

  /// Check if key exists in box
  bool containsKey({
    required String boxName,
    required String key,
  }) {
    try {
      if (!_isInitialized) return false;
      final box = _getBox(boxName);
      if (box == null) return false;
      return box.containsKey(key);
    } catch (e) {
      print('Hive contains key error: $e');
      return false;
    }
  }

  /// Get box length
  int getLength(String boxName) {
    try {
      if (!_isInitialized) return 0;
      final box = _getBox(boxName);
      if (box == null) return 0;
      return box.length;
    } catch (e) {
      print('Hive get length error: $e');
      return 0;
    }
  }

  /// Save multiple items
  Future<void> saveAll({
    required String boxName,
    required Map<String, dynamic> items,
  }) async {
    try {
      if (!_isInitialized) return;
      final box = _getBox(boxName);
      if (box == null) return;
      await box.putAll(items);
    } catch (e) {
      print('Hive save all error: $e');
      // Don't throw, just log - caching is optional
    }
  }

  /// Delete multiple items
  Future<void> deleteAll({
    required String boxName,
    required List<String> keys,
  }) async {
    try {
      if (!_isInitialized) return;
      final box = _getBox(boxName);
      if (box == null) return;
      await box.deleteAll(keys);
    } catch (e) {
      print('Hive delete all error: $e');
      // Don't throw, just log - caching is optional
    }
  }

  /// Cache with expiration
  Future<void> cacheWithExpiration({
    required String boxName,
    required String key,
    required dynamic value,
    required Duration duration,
  }) async {
    try {
      if (!_isInitialized) return;
      final cacheBox = _getBox(AppConstants.hiveBoxCache);
      if (cacheBox == null) return;
      final expirationTime =
          DateTime.now().add(duration).millisecondsSinceEpoch;

      await cacheBox.put(
        key,
        {
          'value': value,
          'expirationTime': expirationTime,
        },
      );

      // Also save to the main box
      await save(boxName: boxName, key: key, value: value);
    } catch (e) {
      print('Hive cache with expiration error: $e');
      // Don't throw, just log - caching is optional
    }
  }

  /// Get cached data if not expired
  dynamic getCached({
    required String key,
    dynamic defaultValue,
  }) {
    try {
      if (!_isInitialized) return defaultValue;
      final cacheBox = _getBox(AppConstants.hiveBoxCache);
      if (cacheBox == null) return defaultValue;
      final cached = cacheBox.get(key);

      if (cached == null) return defaultValue;

      final expirationTime = cached['expirationTime'] as int;
      final now = DateTime.now().millisecondsSinceEpoch;

      if (now > expirationTime) {
        // Cache expired, delete it
        cacheBox.delete(key);
        return defaultValue;
      }

      return cached['value'] ?? defaultValue;
    } catch (e) {
      print('Hive get cached error: $e');
      return defaultValue;
    }
  }

  /// Check if cache is valid
  bool isCacheValid(String key) {
    try {
      if (!_isInitialized) return false;
      final cacheBox = _getBox(AppConstants.hiveBoxCache);
      if (cacheBox == null) return false;
      final cached = cacheBox.get(key);

      if (cached == null) return false;

      final expirationTime = cached['expirationTime'] as int;
      final now = DateTime.now().millisecondsSinceEpoch;

      return now <= expirationTime;
    } catch (e) {
      print('Hive is cache valid error: $e');
      return false;
    }
  }

  /// Clear expired cache
  Future<void> clearExpiredCache() async {
    try {
      if (!_isInitialized) return;
      final cacheBox = _getBox(AppConstants.hiveBoxCache);
      if (cacheBox == null) return;
      final now = DateTime.now().millisecondsSinceEpoch;
      final keysToDelete = <String>[];

      for (final key in cacheBox.keys) {
        final cached = cacheBox.get(key);
        if (cached != null) {
          final expirationTime = cached['expirationTime'] as int;
          if (now > expirationTime) {
            keysToDelete.add(key as String);
          }
        }
      }

      if (keysToDelete.isNotEmpty) {
        await cacheBox.deleteAll(keysToDelete);
        print('Cleared ${keysToDelete.length} expired cache entries');
      }
    } catch (e) {
      print('Hive clear expired cache error: $e');
    }
  }

  /// Clear all cache
  Future<void> clearAllCache() async {
    try {
      await clearBox(AppConstants.hiveBoxCache);
      print('All cache cleared');
    } catch (e) {
      print('Hive clear all cache error: $e');
      throw Exception('Failed to clear all cache: ${e.toString()}');
    }
  }

  /// Save settings
  Future<void> saveSetting(String key, dynamic value) async {
    await save(
      boxName: AppConstants.hiveBoxSettings,
      key: key,
      value: value,
    );
  }

  /// Get setting
  dynamic getSetting(String key, {dynamic defaultValue}) {
    return get(
      boxName: AppConstants.hiveBoxSettings,
      key: key,
      defaultValue: defaultValue,
    );
  }

  /// Close all boxes
  Future<void> closeAll() async {
    try {
      await Hive.close();
      print('All Hive boxes closed');
    } catch (e) {
      print('Hive close all error: $e');
      throw Exception('Failed to close boxes: ${e.toString()}');
    }
  }

  /// Compact boxes to reduce storage
  Future<void> compact() async {
    try {
      for (final boxName in [
        AppConstants.hiveBoxUsers,
        AppConstants.hiveBoxSemesters,
        AppConstants.hiveBoxCourses,
        AppConstants.hiveBoxGroups,
        AppConstants.hiveBoxAnnouncements,
        AppConstants.hiveBoxAssignments,
        AppConstants.hiveBoxQuizzes,
        AppConstants.hiveBoxMaterials,
        AppConstants.hiveBoxNotifications,
        AppConstants.hiveBoxCache,
        AppConstants.hiveBoxSettings,
      ]) {
        if (Hive.isBoxOpen(boxName)) {
          await _getBox(boxName)?.compact();
        }
      }
      print('All boxes compacted');
    } catch (e) {
      print('Hive compact error: $e');
    }
  }

  /// Get storage info
  Map<String, int> getStorageInfo() {
    final info = <String, int>{};

    for (final boxName in [
      AppConstants.hiveBoxUsers,
      AppConstants.hiveBoxSemesters,
      AppConstants.hiveBoxCourses,
      AppConstants.hiveBoxGroups,
      AppConstants.hiveBoxAnnouncements,
      AppConstants.hiveBoxAssignments,
      AppConstants.hiveBoxQuizzes,
      AppConstants.hiveBoxMaterials,
      AppConstants.hiveBoxNotifications,
      AppConstants.hiveBoxCache,
      AppConstants.hiveBoxSettings,
    ]) {
      if (Hive.isBoxOpen(boxName)) {
        info[boxName] = getLength(boxName);
      }
    }

    return info;
  }

  // ==================== NOTIFICATION-SPECIFIC METHODS ====================

  /// Save a notification to Hive cache
  Future<void> saveNotification(NotificationModel notification) async {
    await save(
      boxName: AppConstants.hiveBoxNotifications,
      key: notification.id,
      value: notification.toJson(),
    );
  }

  /// Get a notification by ID from Hive cache
  Future<NotificationModel?> getNotificationById(String notificationId) async {
    final data = get(
      boxName: AppConstants.hiveBoxNotifications,
      key: notificationId,
    );
    if (data == null) return null;
    return NotificationModel.fromJson(Map<String, dynamic>.from(data));
  }

  /// Get all notifications for a user from Hive cache
  Future<List<NotificationModel>> getNotifications({String? userId}) async {
    try {
      final allValues = getAllValues(AppConstants.hiveBoxNotifications);
      final notifications = <NotificationModel>[];

      for (final value in allValues) {
        try {
          final notification =
              NotificationModel.fromJson(Map<String, dynamic>.from(value));
          if (userId == null || notification.userId == userId) {
            notifications.add(notification);
          }
        } catch (e) {
          // Skip invalid entries
          print('Error parsing notification: $e');
        }
      }

      return notifications;
    } catch (e) {
      print('Error getting notifications from cache: $e');
      return [];
    }
  }

  /// Delete a notification from Hive cache
  Future<void> deleteNotification(String notificationId) async {
    await delete(
      boxName: AppConstants.hiveBoxNotifications,
      key: notificationId,
    );
  }

  /// Clear all notifications for a user from Hive cache
  Future<void> clearNotifications(String userId) async {
    try {
      final allNotifications = await getNotifications(userId: userId);
      final keysToDelete =
          allNotifications.map((notification) => notification.id).toList();
      await deleteAll(
        boxName: AppConstants.hiveBoxNotifications,
        keys: keysToDelete,
      );
    } catch (e) {
      print('Error clearing notifications: $e');
    }
  }
}

import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:hive_flutter/hive_flutter.dart';
import '../config/app_constants.dart';
import '../models/user_model.dart';
import '../models/semester_model.dart';
import '../models/course_model.dart';
import '../models/group_model.dart';
import '../models/announcement_model.dart';
import '../models/assignment_model.dart';
import '../models/assignment_submission_model.dart';
import '../models/quiz_model.dart';
import '../models/question_model.dart';
import '../models/quiz_submission_model.dart';
import '../models/material_model.dart';
import '../models/forum_topic_model.dart';
import '../models/forum_reply_model.dart';
import '../models/message_model.dart';
import '../models/notification_model.dart';

/// Hive Service
/// Handles offline caching and local data storage
class HiveService {
  static HiveService? _instance;
  bool _isInitialized = false;

  HiveService._();

  static HiveService get instance {
    _instance ??= HiveService._();
    return _instance!;
  }

  /// Initialize Hive and open boxes
  Future<void> initialize() async {
    // Check if already initialized to prevent duplicate initialization
    if (_isInitialized) {
      print('Hive already initialized');
      return;
    }

    try {
      // Initialize Hive for Flutter
      await Hive.initFlutter();

      // Register adapters (generated by build_runner)
      if (!Hive.isAdapterRegistered(AppConstants.hiveTypeIdUser)) {
        Hive.registerAdapter(UserModelAdapter());
      }
      if (!Hive.isAdapterRegistered(AppConstants.hiveTypeIdSemester)) {
        Hive.registerAdapter(SemesterModelAdapter());
      }
      if (!Hive.isAdapterRegistered(AppConstants.hiveTypeIdCourse)) {
        Hive.registerAdapter(CourseModelAdapter());
      }
      if (!Hive.isAdapterRegistered(AppConstants.hiveTypeIdGroup)) {
        Hive.registerAdapter(GroupModelAdapter());
      }
      if (!Hive.isAdapterRegistered(AppConstants.hiveTypeIdAnnouncement)) {
        Hive.registerAdapter(AnnouncementModelAdapter());
      }
      if (!Hive.isAdapterRegistered(AppConstants.hiveTypeIdAssignment)) {
        Hive.registerAdapter(AssignmentModelAdapter());
      }
      if (!Hive.isAdapterRegistered(AppConstants.hiveTypeIdAssignmentSubmission)) {
        Hive.registerAdapter(AssignmentSubmissionModelAdapter());
      }
      if (!Hive.isAdapterRegistered(AppConstants.hiveTypeIdQuiz)) {
        Hive.registerAdapter(QuizModelAdapter());
      }
      if (!Hive.isAdapterRegistered(AppConstants.hiveTypeIdQuestion)) {
        Hive.registerAdapter(QuestionModelAdapter());
      }
      if (!Hive.isAdapterRegistered(AppConstants.hiveTypeIdQuizSubmission)) {
        Hive.registerAdapter(QuizSubmissionModelAdapter());
      }
      if (!Hive.isAdapterRegistered(AppConstants.hiveTypeIdMaterial)) {
        Hive.registerAdapter(MaterialModelAdapter());
      }
      if (!Hive.isAdapterRegistered(AppConstants.hiveTypeIdForumTopic)) {
        Hive.registerAdapter(ForumTopicModelAdapter());
      }
      if (!Hive.isAdapterRegistered(AppConstants.hiveTypeIdForumReply)) {
        Hive.registerAdapter(ForumReplyModelAdapter());
      }
      if (!Hive.isAdapterRegistered(AppConstants.hiveTypeIdMessage)) {
        Hive.registerAdapter(MessageModelAdapter());
      }
      if (!Hive.isAdapterRegistered(AppConstants.hiveTypeIdNotification)) {
        Hive.registerAdapter(NotificationModelAdapter());
      }

      // Open boxes
      await _openBoxes();

      _isInitialized = true;
      print('Hive initialized successfully');
    } catch (e) {
      print('Hive initialization error: $e');
      // On web, Hive initialization might fail due to platform limitations
      // We'll continue without caching rather than blocking the app
      if (kIsWeb) {
        print('Warning: Hive caching disabled on web platform');
        _isInitialized = false;
      } else {
        throw Exception('Failed to initialize Hive: ${e.toString()}');
      }
    }
  }

  /// Open all Hive boxes
  Future<void> _openBoxes() async {
    await Hive.openBox(AppConstants.hiveBoxUsers);
    await Hive.openBox(AppConstants.hiveBoxSemesters);
    await Hive.openBox(AppConstants.hiveBoxCourses);
    await Hive.openBox(AppConstants.hiveBoxGroups);
    await Hive.openBox(AppConstants.hiveBoxAnnouncements);
    await Hive.openBox(AppConstants.hiveBoxAssignments);
    await Hive.openBox(AppConstants.hiveBoxQuizzes);
    await Hive.openBox(AppConstants.hiveBoxMaterials);
    await Hive.openBox(AppConstants.hiveBoxNotifications);
    await Hive.openBox(AppConstants.hiveBoxCache);
    await Hive.openBox(AppConstants.hiveBoxSettings);
  }

  /// Get a box by name
  Box? _getBox(String boxName) {
    if (!_isInitialized) {
      return null;
    }
    if (!Hive.isBoxOpen(boxName)) {
      print('Warning: Box $boxName is not open');
      return null;
    }
    return Hive.box(boxName);
  }

  /// Save data to cache
  Future<void> save({
    required String boxName,
    required String key,
    required dynamic value,
  }) async {
    try {
      if (!_isInitialized) {
        print('Hive not initialized, skipping save');
        return;
      }
      final box = _getBox(boxName);
      if (box == null) return;
      await box.put(key, value);
    } catch (e) {
      print('Hive save error: $e');
      // Don't throw, just log - caching is optional
    }
  }

  /// Get data from cache
  dynamic get({
    required String boxName,
    required String key,
    dynamic defaultValue,
  }) {
    try {
      if (!_isInitialized) {
        return defaultValue;
      }
      final box = _getBox(boxName);
      if (box == null) return defaultValue;
      return box.get(key, defaultValue: defaultValue);
    } catch (e) {
      print('Hive get error: $e');
      return defaultValue;
    }
  }

  /// Delete data from cache
  Future<void> delete({
    required String boxName,
    required String key,
  }) async {
    try {
      if (!_isInitialized) return;
      final box = _getBox(boxName);
      if (box == null) return;
      await box.delete(key);
    } catch (e) {
      print('Hive delete error: $e');
      // Don't throw, just log - caching is optional
    }
  }

  /// Clear all data from a box
  Future<void> clearBox(String boxName) async {
    try {
      if (!_isInitialized) return;
      final box = _getBox(boxName);
      if (box == null) return;
      await box.clear();
    } catch (e) {
      print('Hive clear box error: $e');
      // Don't throw, just log - caching is optional
    }
  }

  /// Get all keys from a box
  List<dynamic> getAllKeys(String boxName) {
    try {
      if (!_isInitialized) return [];
      final box = _getBox(boxName);
      if (box == null) return [];
      return box.keys.toList();
    } catch (e) {
      print('Hive get all keys error: $e');
      return [];
    }
  }

  /// Get all values from a box
  List<dynamic> getAllValues(String boxName) {
    try {
      if (!_isInitialized) return [];
      final box = _getBox(boxName);
      if (box == null) return [];
      return box.values.toList();
    } catch (e) {
      print('Hive get all values error: $e');
      return [];
    }
  }

  /// Check if key exists in box
  bool containsKey({
    required String boxName,
    required String key,
  }) {
    try {
      if (!_isInitialized) return false;
      final box = _getBox(boxName);
      if (box == null) return false;
      return box.containsKey(key);
    } catch (e) {
      print('Hive contains key error: $e');
      return false;
    }
  }

  /// Get box length
  int getLength(String boxName) {
    try {
      if (!_isInitialized) return 0;
      final box = _getBox(boxName);
      if (box == null) return 0;
      return box.length;
    } catch (e) {
      print('Hive get length error: $e');
      return 0;
    }
  }

  /// Save multiple items
  Future<void> saveAll({
    required String boxName,
    required Map<String, dynamic> items,
  }) async {
    try {
      if (!_isInitialized) return;
      final box = _getBox(boxName);
      if (box == null) return;
      await box.putAll(items);
    } catch (e) {
      print('Hive save all error: $e');
      // Don't throw, just log - caching is optional
    }
  }

  /// Delete multiple items
  Future<void> deleteAll({
    required String boxName,
    required List<String> keys,
  }) async {
    try {
      if (!_isInitialized) return;
      final box = _getBox(boxName);
      if (box == null) return;
      await box.deleteAll(keys);
    } catch (e) {
      print('Hive delete all error: $e');
      // Don't throw, just log - caching is optional
    }
  }

  /// Cache with expiration
  Future<void> cacheWithExpiration({
    required String boxName,
    required String key,
    required dynamic value,
    required Duration duration,
  }) async {
    try {
      if (!_isInitialized) return;
      final cacheBox = _getBox(AppConstants.hiveBoxCache);
      if (cacheBox == null) return;
      final expirationTime =
          DateTime.now().add(duration).millisecondsSinceEpoch;

      await cacheBox.put(
        key,
        {
          'value': value,
          'expirationTime': expirationTime,
        },
      );

      // Also save to the main box
      await save(boxName: boxName, key: key, value: value);
    } catch (e) {
      print('Hive cache with expiration error: $e');
      // Don't throw, just log - caching is optional
    }
  }

  /// Get cached data if not expired
  dynamic getCached({
    required String key,
    dynamic defaultValue,
  }) {
    try {
      if (!_isInitialized) return defaultValue;
      final cacheBox = _getBox(AppConstants.hiveBoxCache);
      if (cacheBox == null) return defaultValue;
      final cached = cacheBox.get(key);

      if (cached == null) return defaultValue;

      final expirationTime = cached['expirationTime'] as int;
      final now = DateTime.now().millisecondsSinceEpoch;

      if (now > expirationTime) {
        // Cache expired, delete it
        cacheBox.delete(key);
        return defaultValue;
      }

      return cached['value'] ?? defaultValue;
    } catch (e) {
      print('Hive get cached error: $e');
      return defaultValue;
    }
  }

  /// Check if cache is valid
  bool isCacheValid(String key) {
    try {
      if (!_isInitialized) return false;
      final cacheBox = _getBox(AppConstants.hiveBoxCache);
      if (cacheBox == null) return false;
      final cached = cacheBox.get(key);

      if (cached == null) return false;

      final expirationTime = cached['expirationTime'] as int;
      final now = DateTime.now().millisecondsSinceEpoch;

      return now <= expirationTime;
    } catch (e) {
      print('Hive is cache valid error: $e');
      return false;
    }
  }

  /// Clear expired cache
  Future<void> clearExpiredCache() async {
    try {
      if (!_isInitialized) return;
      final cacheBox = _getBox(AppConstants.hiveBoxCache);
      if (cacheBox == null) return;
      final now = DateTime.now().millisecondsSinceEpoch;
      final keysToDelete = <String>[];

      for (final key in cacheBox.keys) {
        final cached = cacheBox.get(key);
        if (cached != null) {
          final expirationTime = cached['expirationTime'] as int;
          if (now > expirationTime) {
            keysToDelete.add(key as String);
          }
        }
      }

      if (keysToDelete.isNotEmpty) {
        await cacheBox.deleteAll(keysToDelete);
        print('Cleared ${keysToDelete.length} expired cache entries');
      }
    } catch (e) {
      print('Hive clear expired cache error: $e');
    }
  }

  /// Clear all cache
  Future<void> clearAllCache() async {
    try {
      await clearBox(AppConstants.hiveBoxCache);
      print('All cache cleared');
    } catch (e) {
      print('Hive clear all cache error: $e');
      throw Exception('Failed to clear all cache: ${e.toString()}');
    }
  }

  /// Save settings
  Future<void> saveSetting(String key, dynamic value) async {
    await save(
      boxName: AppConstants.hiveBoxSettings,
      key: key,
      value: value,
    );
  }

  /// Get setting
  dynamic getSetting(String key, {dynamic defaultValue}) {
    return get(
      boxName: AppConstants.hiveBoxSettings,
      key: key,
      defaultValue: defaultValue,
    );
  }

  /// Close all boxes
  Future<void> closeAll() async {
    try {
      await Hive.close();
      print('All Hive boxes closed');
    } catch (e) {
      print('Hive close all error: $e');
      throw Exception('Failed to close boxes: ${e.toString()}');
    }
  }

  /// Compact boxes to reduce storage
  Future<void> compact() async {
    try {
      for (final boxName in [
        AppConstants.hiveBoxUsers,
        AppConstants.hiveBoxSemesters,
        AppConstants.hiveBoxCourses,
        AppConstants.hiveBoxGroups,
        AppConstants.hiveBoxAnnouncements,
        AppConstants.hiveBoxAssignments,
        AppConstants.hiveBoxQuizzes,
        AppConstants.hiveBoxMaterials,
        AppConstants.hiveBoxNotifications,
        AppConstants.hiveBoxCache,
        AppConstants.hiveBoxSettings,
      ]) {
        if (Hive.isBoxOpen(boxName)) {
          await _getBox(boxName)?.compact();
        }
      }
      print('All boxes compacted');
    } catch (e) {
      print('Hive compact error: $e');
    }
  }

  /// Get storage info
  Map<String, int> getStorageInfo() {
    final info = <String, int>{};

    for (final boxName in [
      AppConstants.hiveBoxUsers,
      AppConstants.hiveBoxSemesters,
      AppConstants.hiveBoxCourses,
      AppConstants.hiveBoxGroups,
      AppConstants.hiveBoxAnnouncements,
      AppConstants.hiveBoxAssignments,
      AppConstants.hiveBoxQuizzes,
      AppConstants.hiveBoxMaterials,
      AppConstants.hiveBoxNotifications,
      AppConstants.hiveBoxCache,
      AppConstants.hiveBoxSettings,
    ]) {
      if (Hive.isBoxOpen(boxName)) {
        info[boxName] = getLength(boxName);
      }
    }

    return info;
  }

  // ==================== NOTIFICATION-SPECIFIC METHODS ====================

  /// Save a notification to Hive cache
  Future<void> saveNotification(NotificationModel notification) async {
    await save(
      boxName: AppConstants.hiveBoxNotifications,
      key: notification.id,
      value: notification.toJson(),
    );
  }

  /// Get a notification by ID from Hive cache
  Future<NotificationModel?> getNotificationById(String notificationId) async {
    final data = get(
      boxName: AppConstants.hiveBoxNotifications,
      key: notificationId,
    );
    if (data == null) return null;
    return NotificationModel.fromJson(Map<String, dynamic>.from(data));
  }

  /// Get all notifications for a user from Hive cache
  Future<List<NotificationModel>> getNotifications({String? userId}) async {
    try {
      final allValues = getAllValues(AppConstants.hiveBoxNotifications);
      final notifications = <NotificationModel>[];

      for (final value in allValues) {
        try {
          final notification =
              NotificationModel.fromJson(Map<String, dynamic>.from(value));
          if (userId == null || notification.userId == userId) {
            notifications.add(notification);
          }
        } catch (e) {
          // Skip invalid entries
          print('Error parsing notification: $e');
        }
      }

      return notifications;
    } catch (e) {
      print('Error getting notifications from cache: $e');
      return [];
    }
  }

  /// Delete a notification from Hive cache
  Future<void> deleteNotification(String notificationId) async {
    await delete(
      boxName: AppConstants.hiveBoxNotifications,
      key: notificationId,
    );
  }

  /// Clear all notifications for a user from Hive cache
  Future<void> clearNotifications(String userId) async {
    try {
      final allNotifications = await getNotifications(userId: userId);
      final keysToDelete =
          allNotifications.map((notification) => notification.id).toList();
      await deleteAll(
        boxName: AppConstants.hiveBoxNotifications,
        keys: keysToDelete,
      );
    } catch (e) {
      print('Error clearing notifications: $e');
    }
  }
}
