import 'package:hive_flutter/hive_flutter.dart';
import '../config/app_constants.dart';

/// Hive Service
/// Handles offline caching and local data storage
class HiveService {
  static HiveService? _instance;

  HiveService._();

  static HiveService get instance {
    _instance ??= HiveService._();
    return _instance!;
  }

  /// Initialize Hive and open boxes
  Future<void> initialize() async {
    try {
      // Initialize Hive for Flutter
      await Hive.initFlutter();

      // Register adapters (will be generated by build_runner)
      // Note: Uncomment after running build_runner
      // Hive.registerAdapter(UserModelAdapter());
      // Hive.registerAdapter(SemesterModelAdapter());
      // Hive.registerAdapter(CourseModelAdapter());
      // Hive.registerAdapter(GroupModelAdapter());
      // Hive.registerAdapter(AnnouncementModelAdapter());
      // Hive.registerAdapter(AssignmentModelAdapter());
      // Hive.registerAdapter(QuizModelAdapter());
      // Hive.registerAdapter(MaterialModelAdapter());
      // Hive.registerAdapter(NotificationModelAdapter());

      // Open boxes
      await _openBoxes();

      print('Hive initialized successfully');
    } catch (e) {
      print('Hive initialization error: $e');
      throw Exception('Failed to initialize Hive: ${e.toString()}');
    }
  }

  /// Open all Hive boxes
  Future<void> _openBoxes() async {
    await Hive.openBox(AppConstants.hiveBoxUsers);
    await Hive.openBox(AppConstants.hiveBoxSemesters);
    await Hive.openBox(AppConstants.hiveBoxCourses);
    await Hive.openBox(AppConstants.hiveBoxGroups);
    await Hive.openBox(AppConstants.hiveBoxAnnouncements);
    await Hive.openBox(AppConstants.hiveBoxAssignments);
    await Hive.openBox(AppConstants.hiveBoxQuizzes);
    await Hive.openBox(AppConstants.hiveBoxMaterials);
    await Hive.openBox(AppConstants.hiveBoxNotifications);
    await Hive.openBox(AppConstants.hiveBoxCache);
    await Hive.openBox(AppConstants.hiveBoxSettings);
  }

  /// Get a box by name
  Box _getBox(String boxName) {
    if (!Hive.isBoxOpen(boxName)) {
      throw Exception('Box $boxName is not open');
    }
    return Hive.box(boxName);
  }

  /// Save data to cache
  Future<void> save({
    required String boxName,
    required String key,
    required dynamic value,
  }) async {
    try {
      final box = _getBox(boxName);
      await box.put(key, value);
    } catch (e) {
      print('Hive save error: $e');
      throw Exception('Failed to save data: ${e.toString()}');
    }
  }

  /// Get data from cache
  dynamic get({
    required String boxName,
    required String key,
    dynamic defaultValue,
  }) {
    try {
      final box = _getBox(boxName);
      return box.get(key, defaultValue: defaultValue);
    } catch (e) {
      print('Hive get error: $e');
      return defaultValue;
    }
  }

  /// Delete data from cache
  Future<void> delete({
    required String boxName,
    required String key,
  }) async {
    try {
      final box = _getBox(boxName);
      await box.delete(key);
    } catch (e) {
      print('Hive delete error: $e');
      throw Exception('Failed to delete data: ${e.toString()}');
    }
  }

  /// Clear all data from a box
  Future<void> clearBox(String boxName) async {
    try {
      final box = _getBox(boxName);
      await box.clear();
    } catch (e) {
      print('Hive clear box error: $e');
      throw Exception('Failed to clear box: ${e.toString()}');
    }
  }

  /// Get all keys from a box
  List<dynamic> getAllKeys(String boxName) {
    try {
      final box = _getBox(boxName);
      return box.keys.toList();
    } catch (e) {
      print('Hive get all keys error: $e');
      return [];
    }
  }

  /// Get all values from a box
  List<dynamic> getAllValues(String boxName) {
    try {
      final box = _getBox(boxName);
      return box.values.toList();
    } catch (e) {
      print('Hive get all values error: $e');
      return [];
    }
  }

  /// Check if key exists in box
  bool containsKey({
    required String boxName,
    required String key,
  }) {
    try {
      final box = _getBox(boxName);
      return box.containsKey(key);
    } catch (e) {
      print('Hive contains key error: $e');
      return false;
    }
  }

  /// Get box length
  int getLength(String boxName) {
    try {
      final box = _getBox(boxName);
      return box.length;
    } catch (e) {
      print('Hive get length error: $e');
      return 0;
    }
  }

  /// Save multiple items
  Future<void> saveAll({
    required String boxName,
    required Map<String, dynamic> items,
  }) async {
    try {
      final box = _getBox(boxName);
      await box.putAll(items);
    } catch (e) {
      print('Hive save all error: $e');
      throw Exception('Failed to save all: ${e.toString()}');
    }
  }

  /// Delete multiple items
  Future<void> deleteAll({
    required String boxName,
    required List<String> keys,
  }) async {
    try {
      final box = _getBox(boxName);
      await box.deleteAll(keys);
    } catch (e) {
      print('Hive delete all error: $e');
      throw Exception('Failed to delete all: ${e.toString()}');
    }
  }

  /// Cache with expiration
  Future<void> cacheWithExpiration({
    required String boxName,
    required String key,
    required dynamic value,
    required Duration duration,
  }) async {
    try {
      final cacheBox = _getBox(AppConstants.hiveBoxCache);
      final expirationTime = DateTime.now().add(duration).millisecondsSinceEpoch;

      await cacheBox.put(
        key,
        {
          'value': value,
          'expirationTime': expirationTime,
        },
      );

      // Also save to the main box
      await save(boxName: boxName, key: key, value: value);
    } catch (e) {
      print('Hive cache with expiration error: $e');
      throw Exception('Failed to cache with expiration: ${e.toString()}');
    }
  }

  /// Get cached data if not expired
  dynamic getCached({
    required String key,
    dynamic defaultValue,
  }) {
    try {
      final cacheBox = _getBox(AppConstants.hiveBoxCache);
      final cached = cacheBox.get(key);

      if (cached == null) return defaultValue;

      final expirationTime = cached['expirationTime'] as int;
      final now = DateTime.now().millisecondsSinceEpoch;

      if (now > expirationTime) {
        // Cache expired, delete it
        cacheBox.delete(key);
        return defaultValue;
      }

      return cached['value'] ?? defaultValue;
    } catch (e) {
      print('Hive get cached error: $e');
      return defaultValue;
    }
  }

  /// Check if cache is valid
  bool isCacheValid(String key) {
    try {
      final cacheBox = _getBox(AppConstants.hiveBoxCache);
      final cached = cacheBox.get(key);

      if (cached == null) return false;

      final expirationTime = cached['expirationTime'] as int;
      final now = DateTime.now().millisecondsSinceEpoch;

      return now <= expirationTime;
    } catch (e) {
      print('Hive is cache valid error: $e');
      return false;
    }
  }

  /// Clear expired cache
  Future<void> clearExpiredCache() async {
    try {
      final cacheBox = _getBox(AppConstants.hiveBoxCache);
      final now = DateTime.now().millisecondsSinceEpoch;
      final keysToDelete = <String>[];

      for (final key in cacheBox.keys) {
        final cached = cacheBox.get(key);
        if (cached != null) {
          final expirationTime = cached['expirationTime'] as int;
          if (now > expirationTime) {
            keysToDelete.add(key as String);
          }
        }
      }

      if (keysToDelete.isNotEmpty) {
        await cacheBox.deleteAll(keysToDelete);
        print('Cleared ${keysToDelete.length} expired cache entries');
      }
    } catch (e) {
      print('Hive clear expired cache error: $e');
    }
  }

  /// Clear all cache
  Future<void> clearAllCache() async {
    try {
      await clearBox(AppConstants.hiveBoxCache);
      print('All cache cleared');
    } catch (e) {
      print('Hive clear all cache error: $e');
      throw Exception('Failed to clear all cache: ${e.toString()}');
    }
  }

  /// Save settings
  Future<void> saveSetting(String key, dynamic value) async {
    await save(
      boxName: AppConstants.hiveBoxSettings,
      key: key,
      value: value,
    );
  }

  /// Get setting
  dynamic getSetting(String key, {dynamic defaultValue}) {
    return get(
      boxName: AppConstants.hiveBoxSettings,
      key: key,
      defaultValue: defaultValue,
    );
  }

  /// Close all boxes
  Future<void> closeAll() async {
    try {
      await Hive.close();
      print('All Hive boxes closed');
    } catch (e) {
      print('Hive close all error: $e');
      throw Exception('Failed to close boxes: ${e.toString()}');
    }
  }

  /// Compact boxes to reduce storage
  Future<void> compact() async {
    try {
      for (final boxName in [
        AppConstants.hiveBoxUsers,
        AppConstants.hiveBoxSemesters,
        AppConstants.hiveBoxCourses,
        AppConstants.hiveBoxGroups,
        AppConstants.hiveBoxAnnouncements,
        AppConstants.hiveBoxAssignments,
        AppConstants.hiveBoxQuizzes,
        AppConstants.hiveBoxMaterials,
        AppConstants.hiveBoxNotifications,
        AppConstants.hiveBoxCache,
        AppConstants.hiveBoxSettings,
      ]) {
        if (Hive.isBoxOpen(boxName)) {
          await _getBox(boxName).compact();
        }
      }
      print('All boxes compacted');
    } catch (e) {
      print('Hive compact error: $e');
    }
  }

  /// Get storage info
  Map<String, int> getStorageInfo() {
    final info = <String, int>{};

    for (final boxName in [
      AppConstants.hiveBoxUsers,
      AppConstants.hiveBoxSemesters,
      AppConstants.hiveBoxCourses,
      AppConstants.hiveBoxGroups,
      AppConstants.hiveBoxAnnouncements,
      AppConstants.hiveBoxAssignments,
      AppConstants.hiveBoxQuizzes,
      AppConstants.hiveBoxMaterials,
      AppConstants.hiveBoxNotifications,
      AppConstants.hiveBoxCache,
      AppConstants.hiveBoxSettings,
    ]) {
      if (Hive.isBoxOpen(boxName)) {
        info[boxName] = getLength(boxName);
      }
    }

    return info;
  }
}
