// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsMNLPrnfg1EYDxwKrg4SuZwudB26Oe5s',
    appId: '1:590588841369:web:690f30a25ad6c5961f1708',
    messagingSenderId: '590588841369',
    projectId: 'elearning-management-b4314',
    authDomain: 'elearning-management-b4314.firebaseapp.com',
    storageBucket: 'elearning-management-b4314.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB8qL9s1vVJlYp6852arml2RuYsxIFtRw',
    appId: '1:590588841369:android:2d95d0aea59382031f1708',
    messagingSenderId: '590588841369',
    projectId: 'elearning-management-b4314',
    storageBucket: 'elearning-management-b4314.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsMNLPrnfg1EYDxwKrg4SuZwudB26Oe5s',
    appId: '1:590588841369:web:431aec787bb0d0021f1708',
    messagingSenderId: '590588841369',
    projectId: 'elearning-management-b4314',
    authDomain: 'elearning-management-b4314.firebaseapp.com',
    storageBucket: 'elearning-management-b4314.appspot.com',
  );
}
